### ISSUE TITLE
FTB Crash by start with newest version of FTB Lib and FTB Quest

### ISSUE THREAD

**Issue by Titoo8899** [FTBTeam/FTB-Utilities#1005]
Hi,
I have only FTB Quest, FTB Lib and Itemfilter in my mods folder with other mods what normal work but the newest version of FTB Quest and FTB Lib make not good thinks.
FTB Lib: 5.4.3.114
FTB Quest: 1.6.1.159
ItemFilter: 1.0.3.12

The Crash Report say a bug in FTBlib.

Crash Report:
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Library  (ftblib)

-------
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/18/19 8:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Library (ftblib)
Caused by: java.lang.NoClassDefFoundError: javafx/scene/image/PixelFormat
	at com.feed_the_beast.ftblib.client.FTBLibClientConfigManager.onResourceManagerReload(FTBLibClientConfigManager.java:37)
	at net.minecraftforge.client.resource.ISelectiveResourceReloadListener.func_110549_a(ISelectiveResourceReloadListener.java:33)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at com.feed_the_beast.ftblib.client.FTBLibClient.preInit(FTBLibClient.java:39)
	at com.feed_the_beast.ftblib.FTBLib.onPreInit(FTBLib.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: javafx.scene.image.PixelFormat
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 346277880 bytes (330 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version               | Source                                                                | Signature                                |
	|:----- |:-------------------------- |:--------------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                | minecraft.jar                                                         | None                                     |
	| UCH   | mcp                        | 9.42                  | minecraft.jar                                                         | None                                     |
	| UCH   | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | better_diving              | 1.3.63                | BetterDiving-1.12.2-1.3.63.jar                                        | None                                     |
	| UCH   | mts                        | 14.3.1                | Immersive+Vehicles-1.12.2-14.3.1.jar                                  | None                                     |
	| UCH   | unuparts                   | 1.11.2                | UNU+Parts+Pack+[MTS]+1.10.2-14.0.0-1.11.2.jar                         | None                                     |
	| UCH   | blackthorne                | 1.11.2                | BlackThorne+Empire+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-1.11.2.jar | None                                     |
	| UCH   | crossbow                   | 1.0.0                 | Crossbow-Mod-1.12.2-1.0.0-fix.jar                                     | None                                     |
	| UCEE  | ftblib                     | 5.4.3.114             | FTBLib-5.4.3.114.jar                                                  | None                                     |
	| UC    | itemfilters                | 1.0.3.12              | ItemFilters-1.0.3.12.jar                                              | None                                     |
	| UC    | ftbquests                  | 1.6.1.159             | FTBQuests-1.6.1.159.jar                                               | None                                     |
	| UC    | holdyerbreath              | 1.12.2-1.1.2          | holdyerbreath-1.12.2-1.1.2.jar                                        | None                                     |
	| UC    | mtsseagullcivilpack        | 2.0.0                 | Immersive+Vehicles+(IV)+Seagull's+civil+pack+1.22.0.jar               | None                                     |
	| UC    | mtsseagullmilitarypack     | 1.4.0                 | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.3.jar             | None                                     |
	| UC    | mtsseagulltrinpartpack     | 1.0.0                 | Immersive+Vehicles+(IV)+Seagull's+trin+parts+pack+1.11.2.jar          | None                                     |
	| UC    | melvinssignpack            | 1.0.0                 | Melvins_Simple_Sign_Pack-Beta-0.0.5.jar                               | None                                     |
	| UC    | mtsofficialpack            | 11.0.0                | MTS_Official_Pack_V11.jar                                             | None                                     |
	| UC    | merlynofficialpack         | 5.4.0                 | Merlyn's+Luxurious+Vehicles+Pack+5.4.jar                              | None                                     |
	| UC    | mmmpack                    | 1.0.3                 | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-14.0.0-1.0.3.jar           | None                                     |
	| UC    | blueboyscaterpillarmtspack | 1.1.0                 | MTS_Caterpillar_Pack_V1.1.1.jar                                       | None                                     |
	| UC    | mtsheavyindustrialbyadamrk | 6.0.0                 | MTS_Heavy_Industrial_by_AdamRK_1.9.0.jar                              | None                                     |
	| UC    | jblavehaero                | 1.0.0                 | MTS_P1_airportpack.jar                                                | None                                     |
	| UC    | t3gssksignspack

**Comment by Boolyman** [comment]
Same issue.
