### ISSUE TITLE
Newest FTBLib crash by middle of the loading of Forge areas

### ISSUE THREAD

**Issue by Titoo8899** [FTBTeam/FTB-Utilities#1007]
Hi,
a new Crash give it from your FTBLib Mod Version: 5.4.3.115. Hope you find the Bug.

Crash Report:
Error: java.lang.NoClassDefFoundError: javafx/scene/Node

---------------------

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 6/18/19 10:01 PM
Description: Initializing game

java.lang.NoClassDefFoundError: javafx/scene/Node
	at com.feed_the_beast.ftbquests.client.FTBQuestsClient.getQuestFile(FTBQuestsClient.java:91)
	at com.feed_the_beast.ftbquests.FTBQuestsCommon.getQuestFile(FTBQuestsCommon.java:18)
	at com.feed_the_beast.ftbquests.item.ItemLootCrate.func_150895_a(ItemLootCrate.java:138)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: javafx.scene.Node
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.feed_the_beast.ftbquests.client.FTBQuestsClient.getQuestFile(FTBQuestsClient.java:91)
	at com.feed_the_beast.ftbquests.FTBQuestsCommon.getQuestFile(FTBQuestsCommon.java:18)
	at com.feed_the_beast.ftbquests.item.ItemLootCrate.func_150895_a(ItemLootCrate.java:138)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 210903176 bytes (201 MB) / 939524096 bytes (896 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version               | Source                                                                | Signature                                |
	|:----- |:-------------------------- |:--------------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                | minecraft.jar                                                         | None                                     |
	| UCH   | mcp                        | 9.42                  | minecraft.jar                                                         | None                                     |
	| UCH   | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | better_diving              | 1.3.63                | BetterDiving-1.12.2-1.3.63.jar                                        | None                                     |
	| UCH   | mts                        | 14.3.1                | Immersive+Vehicles-1.12.2-14.3.1.jar                                  | None                                     |
	| UCH   | unuparts                   | 1.11.2                | UNU+Parts+Pack+[MTS]+1.10.2-14.0.0-1.11.2.jar                         | None                                     |
	| UCH   | blackthorne                | 1.11.2                | BlackThorne+Empire+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-1.11.2.jar | None                                     |
	| UCH   | crossbow                   | 1.0.0                 | Crossbow-Mod-1.12.2-1.0.0-fix.jar                                     | None                                     |
	| UCH   | ftblib                     | 5.4.3.115             | FTBLib-5.4.3.115.jar                                                  | None                                     |
	| UCH   | itemfilters                | 1.0.3.12              | ItemFilters-1.0.3.12.jar                                              | None                                     |
	| UCH   | ftbquests                  | 1.6.1.159             | FTBQuests-1.6.1.159.jar                                               | None                                     |
	| UCH   | holdyerbreath              | 1.12.2-1.1.2          | holdyerbreath-1.12.2-1.1.2.jar                                        | None                                     |
	| UCH   | mtsseagullcivilpack        | 2.0.0                 | Immersive+Vehicles+(IV)+Seagull's+civil+pack+1.22.0.jar               | None                                     |
	| UCH   | mtsseagullmilitarypack     | 1.4.0                 | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.3.jar             | None                                     |
	| UCH   | mtsseagulltrinpartpack     | 1.0.0                 | Immersive+Vehicles+(IV)+Seagull's+trin+parts+pack+1.11.2.jar          | None                                     |
	| UCH   | melvinssignpack            | 1.0.0                 | Melvins_Simple_Sign_Pack-Beta-0.0.5.jar                               | None                                     |
	| UCH   | mtsofficialpack            | 11.0.0                | MTS_Official_Pack_V11.jar                                             | None                                     |
	| UCH   | merlynofficialpack         | 5.4.0                 | Merlyn's+Luxurious+Vehicles+Pack+5.4.jar                              | None                                     |
	| UCH   | mmmpack                    | 1.0.3                 | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-14.0.0-1.0.3.jar           | None                                     |
	| UCH   | blueboyscaterpillarmtspack | 1.1.0                 | MTS_Caterpillar_Pack_V1.1.1.jar                                       | None                                     |
	| UCH   | mtsheavyindustrialbyadamrk | 6.0.0                 | MTS_Heavy_Industrial_by_AdamRK_1.9.0.jar                              | None                                     |
	| UCH   | jblavehaero                | 1.0.0                 | MTS_P1_airportpack.jar                                                | None                                     |
	| UCH   | t3gssksignspack            | 1.0.1                 | Tim3Game's+European+Signs+Pack+1.0.1.jar                              | None                                     |
	| UCH   | nofog                      | 1.12.2-1.12.2-1.0.3.0 | NoFog-1.12.2b3.jar                                                    | 0bf221d944c89aaf3ccb7b8315148f222be50739 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by Titoo8899** [comment]
All bugs fix.
