### ISSUE TITLE
Crashs while loading singleplayer

### ISSUE THREAD

**Issue by IceflowRE** [FTBTeam/FTB-Utilities#1035]
Minecraft 1.12.2
Forgemod: 14.23.5.2846

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.5.0-build.0402.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/4/19 6:10 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Utilities (ftbutilities)
Caused by: java.lang.NullPointerException
	at com.tlf.HN.commands.CommandName.func_71518_a(CommandName.java:42)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_71518_a(CommandOverride.java:76)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.<init>(CommandOverride.java:50)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.create(CommandOverride.java:36)
	at com.feed_the_beast.ftbutilities.FTBUtilities.onServerStarted(FTBUtilities.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9280592648 bytes (8850 MB) / 15946219520 bytes (15207 MB) up to 15946219520 bytes (15207 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16g -Xms8g -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 109 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version                  | Source                                             | Signature                                |
	|:------- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA  | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCHIJA  | forge                | 14.23.5.2846             | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCHIJA  | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| LCHIJA  | micdoodlecore        |                          | minecraft.jar                                      | None                                     |
	| LCHIJA  | opencomputers|core   | 1.7.4.153                | minecraft.jar                                      | None                                     |
	| LCHIJA  | dsurroundcore        | 3.5.4.3                  | minecraft.jar                                      | None                                     |
	| LCHIJA  | orbis-lib            | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build127.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA  | aether               | 0.2.6                    | aether_ii-1.12.2-0.2.6+build127-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA  | antiqueatlas         | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA  | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA  | ctm                  | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA  | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA  | aroma1997core        | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA  | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA  | quark                | r1.6-177                 | Quark-r1.6-177.jar                                 | None                                     |
	| LCHIJA  | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA  | battletowers         | 1.6.5                    | BattleTowers-1.12.2.jar                            | None                                     |
	| LCHIJA  | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA  | ic2                  | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA  | forestry             | 5.8.2.394                | forestry_1.12.2-5.8.2.394.jar                      | None                                     |
	| LCHIJA  | binniecore           | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | binniedesign         | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | genetics             | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | botany               | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | extrabees            | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | extratrees           | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LCHIJA  | bloodmoon            | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA  | bookshelf            | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | codechickenlib       | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | chickenchunks        | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA  | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | cofhcore             | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCHIJA  | cofhworld            | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA  | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA  | twilightforest       | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
	| LCHIJA  | tconstruct           | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                   | None                                     |
	| LCHIJA  | conarm               | 1.2.4                    | conarm-1.12.2-1.2.4.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA  | controlling          | 3.0.7                    | Controlling-3.0.7.jar                              | None                                     |
	| LCHIJA  | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA  | coroutil             | 1.12.1-1.2.32            | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA  | configmod            | v1.0                     | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA  | ding                 | 1.0.1                    | Ding-1.12.1-1.0.1.jar                              | None                                     |
	| LCHIJA  | discordsuite         | 2.2.4                    | DiscordSuite-2.2.4.jar                             | None                                     |
	| LCHIJA  | dynamictrees         | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                      | None                                     |
	| LCHIJA  | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zf.jar                    | None                                     |
	| LCHIJA  | dynamictreesphc      | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                   | None                                     |
	| LCHIJA  | rustic               | 1.1.1                    | rustic-1.1.1.jar                                   | None                                     |
	| LCHIJA  | dynamictreestc       | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                   | None                                     |
	| LCHIJA  | energyconverters     | 1.3.0.15                 | energyconverters_1.12.2-1.3.0.15.jar               | None                                     |
	| LCHIJA  | thermalfoundation    | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | immersiveengineering | 0.12-91                  | ImmersiveEngineering-0.12-91.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA  | engineersdoors       | 0.8.0                    | engineers_doors-1.12.2-0.8.0.jar                   | None                                     |
	| LCHIJA  | galacticraftcore     | 4.0.2.236                | GalacticraftCore-1.12.2-4.0.2.236.jar              | None                                     |
	| LCHIJA  | galacticraftplanets  | 4.0.2.236                | Galacticraft-Planets-1.12.2-4.0.2.236.jar          | None                                     |
	| LCHIJA  | mjrlegendslib        | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA  | extraplanets         | 1.12.2-0.5.6             | ExtraPlanets-1.12.2-0.5.6.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA  | farseek              | 2.3.2                    | Farseek-1.12-2.3.2.jar                             | None                                     |
	| LCHIJA  | foamflower           | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1.jar                | None                                     |
	| LCHIJA  | forgeendertech       | 1.12.2-4.4.22.2          | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar      | None                                     |
	| LCHIJA  | forgelin             | 1.8.3                    | Forgelin-1.8.3.jar                                 | None                                     |
	| LCHIJA  | ftblib               | 5.4.3.133                | FTBLib-5.4.3.133.jar                               | None                                     |
	| LCHIJAE | ftbutilities         | 5.4.0.102                | FTBUtilities-5.4.0.102.jar                         | None                                     |
	| LCHIJA  | ftbbackups           | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar                    | None                                     |
	| LCHIJA  | hardcoredarkness     | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA  | hidenames            | 1.4                      | HideNames-1.12-1.4.jar                             | None                                     |
	| LCHIJA  | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA  | icbmclassic          | 1.12.2-3.3.0.65          | ICBM-classic-1.12.2-3.3.0b65.jar                   | None                                     |
	| LCHIJA  | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA  | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
	| LCHIJA  | trackapi             | 1.1                      | TrackAPI-1.1_1.12.jar                              | None                                     |
	| LCHIJA  | immersiverailroading | 1.6.1                    | ImmersiveRailroading-1.6.1_1.12-1138.jar           | None                                     |
	| LCHIJA  | instantunify         | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                      | None                                     |
	| LCHIJA  | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA  | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA  | jeresources          | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCHIJA  | magneticraft         | 2.7.0                    | Magneticraft_1.12-2.8.1-dev.jar                    | None                                     |
	| LCHIJA  | modelloader          | 1.1.7                    | modelloader-1.1.7.jar                              | None                                     |
	| LCHIJA  | morpheus             | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
	| LCHIJA  | shetiphiancore       | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                    | None                                     |
	| LCHIJA  | multistorage         | 1.4.14                   | multistorage-1.12.0-1.4.14.jar                     | None                                     |
	| LCHIJA  | recipehandler        | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJA  | nuclearcraft         | 2.18h                    | NuclearCraft-2.18h-1.12.2.jar                      | None                                     |
	| LCHIJA  | opencomputers        | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar               | None                                     |
	| LCHIJA  | patchouli            | 1.0-20                   | Patchouli-1.0-20.jar                               | None                                     |
	| LCHIJA  | pneumaticcraft       | 1.12.2-0.11.5-371        | pneumaticcraft-repressurized-1.12.2-0.11.5-371.jar | None                                     |
	| LCHIJA  | reccomplex           | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                       | None                                     |
	| LCHIJA  | simplyarrows         | 1.0.4                    | SimplyArrows-1.12.2-1.0.4.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | spawntemple          | 2.1                      | SpawnTemple-v.2.1-mc1.12.jar                       | None                                     |
	| LCHIJA  | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
	| LCHIJA  | tallgates            | 1.0.0                    | TallGates-1.12.2-1.0.0.1.jar                       | None                                     |
	| LCHIJA  | thermalexpansion     | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | thermaldynamics      | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA  | tombstone            | 3.5.6                    | tombstone-3.5.6-1.12.2.jar                         | None                                     |
	| LCHIJA  | uteamcore            | 2.2.4.107                | u_team_core-1.12.2-2.2.4.107.jar                   | None                                     |
	| LCHIJA  | unloader             | 1.2.0                    | unloader-1.2.0.jar                                 | None                                     |
	| LCHIJA  | usefulbackpacks      | 1.5.1.35                 | useful_backpacks-1.12.2-1.5.1.35.jar               | None                                     |
	| LCHIJA  | vending              | 1.12.2-3.0.1.2           | vending-1.12.2-3.0.1.2.jar                         | None                                     |
	| LCHIJA  | wanionlib            | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
	| LCHIJA  | zombieawareness      | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                 | None                                     |
	| LCHIJA  | phosphor-lighting    | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA  | orelib               | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | dsurround            | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA  | adchimneys           | 1.12.2-3.5.5.0           | AdChimneys-1.12.2-3.5.5.0-build.0402.jar           | None                                     |
	| LCHIJA  | unidict              | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (AdChimneys-1.12.2-3.5.5.0-build.0402.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  farseek.core.FarseekClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 431.60
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Spiderfoxtail** [comment]
I had this crash when using FTB Utilities and Hide Names.

**Comment by RubenMasAlmira** [comment]
I have the same issue than you,when I use FTB Utilities and Hide Names that exception appears,anyone can help me?
