### ISSUE TITLE
FTBLib latest upload wrong version number

### ISSUE THREAD

**Issue by Gamertech** [FTBTeam/FTB-Utilities#1046]
FTB Utilities 5.4.0.118 has a dependency on FTBLib 5.4.3.152, but the latest file was named 5.4.3.2.

FTBU can't find its dependancy and fails to the missing dependancy screen on load.

**Comment by Gryffen1971** [comment]
> FTB Utilities 5.4.0.118 has a dependency on FTBLib 5.4.3.152, but the latest file was named 5.4.3.2.
> 
> FTBU can't find its dependancy and fails to the missing dependancy screen on load.

I received the same message.

FTB Utilitiles 5.4.0.118 has a dependency on FTBLib 5.4.3.152 or above (you have 5.4.3.2)

Also, here is the entry in the 'lastest.log' file when it occured;
[22:25:39] [Client thread/FATAL]: net.minecraftforge.fml.common.MissingModsException: Mod ftbutilities (FTB Utilities) requires [ftblib@[5.4.3.152,)]
[22:25:39] [Client thread/ERROR]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod ftbutilities (FTB Utilities) requires [ftblib@[5.4.3.152,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:25:39] [Client thread/WARN]: EventBus 0 shutting down - future events will not be posted.

**Comment by TheNoseOfSauron** [comment]
Same issue here. I think the file for .152 was misnamed as .2

**Comment by WH17EW0LF** [comment]
I tried rolling back and now the whole modpack crashes at launch. Anyone have an ETA on when this will be fixed?

**Comment by TheNoseOfSauron** [comment]
Works for me if I roll FTBLib back 2 version and FTB Utils back 1 version

**Comment by WH17EW0LF** [comment]
ah, thank you, this worked. I obviously wasnt rolling back far enough.

**Comment by Serva95** [comment]
Same issue.  I think the file actually named .2 needs to be named .200 or .201.
