### ISSUE TITLE
[Crash] CTD when breaking a block at 0, 0 in new server

### ISSUE THREAD

**Issue by Codingale** [FTBTeam/FTB-Utilities#1051]
**Full Stack Trace**: https://paste.md-5.net/egilutoviz.rb
Short Snippet:
```
// There are four lights! ;)

Time: 11/26/19 7:30 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler.hasPermission(FTBUtilitiesPermissionHandler.java:51)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.entity.player.EntityPlayer.func_189808_dh(EntityPlayer.java:42070)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
https://github.com/FTBTeam/FTB-Utilities/blob/5b2e4666f8484405b7dc44393801e30af304c977/src/main/java/com/feed_the_beast/ftbutilities/ranks/FTBUtilitiesPermissionHandler.java#L51

Modified [20 days ago ](https://github.com/FTBTeam/FTB-Utilities/commit/6ba40e6be71308cc9e9ce7a3048d52ffe7b1b402) by @LatvianModder (courtesy summon)

Seems related to #1047 also, unsure however.

**Comment by LatvianModder** [comment]
Fixed in version 123
