### ISSUE TITLE
[1.12.2] FTB Backup failing

### ISSUE THREAD

**Issue by Archadimus** [FTBTeam/FTB-Utilities#1064]
When running a manual backup, it says

`World saving failed!` ingame.

in the server console, it spews:

`[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=File IO Thread, priority=1, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:136)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:4269)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at com.feed_the_beast.mods.ftbbackups.Backups.doBackup(Backups.java:213)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at com.feed_the_beast.mods.ftbbackups.Backups.lambda$run$1(Backups.java:184)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
[21:29:47] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.mods.ftbbackups.Backups:doBackup:220]:         at java.lang.Thread.run(Thread.java:748)
`

**Comment by gdharron** [comment]
I have the same issue that just started today randomly. Didn't change much at all today so not sure why this broke all of a sudden.
Spongeforge server running FTB revelation 3.4.0
