### ISSUE TITLE
"<player> is not online!" Not allowing player to create team, and makes it impossible for other players to connect while that player is on the server

### ISSUE THREAD

**Issue by Gearhardt** [FTBTeam/FTB-Utilities#1067]
Every time one of my players is connected to my server, it makes it impossible for other players to connect, but if that player logs out, then the other player are allowed to join, even if that player comes back after they have successfully connected.

Error output:

```
04.02 16:38:26 [Server] INFO java.lang.NullPointerException: Gearhardt is not online!
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getPlayer(ForgePlayer.java:265) ~[ForgePlayer.class:?]
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftbutilities.data.FTBUtilitiesPlayerData.clearCache(FTBUtilitiesPlayerData.java:316) ~[FTBUtilitiesPlayerData.class:?]
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftblib.lib.data.NBTDataStorage.clearCache(NBTDataStorage.java:123) ~[NBTDataStorage.class:?]
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftblib.lib.data.ForgePlayer.clearCache(ForgePlayer.java:105) ~[ForgePlayer.class:?]
04.02 16:38:26 [Server] INFO at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_212]
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftblib.lib.data.Universe.clearCache(Universe.java:842) ~[Universe.class:?]
04.02 16:38:26 [Server] INFO at com.feed_the_beast.ftblib.command.team.CmdCreate.func_184881_a(CmdCreate.java:80) ~[CmdCreate.class:?]
04.02 16:38:26 [Server] INFO at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:164) ~[CommandTreeBase.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
04.02 16:38:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
04.02 16:38:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
04.02 16:38:26 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
04.02 16:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
04.02 16:38:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by blacksages** [comment]
I can confirm I have the same problem

**Comment by Bubillo** [comment]
I have the same error, any solution?

**Comment by blacksages** [comment]
I used another modpack, it worked for whatever reason x)

**Comment by MikeHollisJr** [comment]
The following converstation about this issue took place today,

https://discordapp.com/channels/166630061217153024/254806806516203520/681895610873675778

Poorly formatted excerpt follows:

VyrXToday at 11:09 AM
It seems FTB:U has had a similar exception under different circumstances reported in the last couple of weeks. I wonder if they're related (https://github.com/FTBTeam/FTB-Utilities/issues/1067)
GitHub
FTBTeam/FTB-Utilities
FTBUtilities mod for Minecraft. Depends on FTBLib. Contribute to FTBTeam/FTB-Utilities development by creating an account on GitHub.

just seeing if theres any other issues now
Mike Hollis JrToday at 11:11 AM
that looks exactly like what I'm getting
VyrXToday at 11:11 AM
what version of FTB:u are you using?
Mike Hollis JrToday at 11:12 AM
> team create mikehollisjr orange
[11:11:24] [Server thread/INFO] [minecraft/DedicatedServer]: You must specify which player you wish to perform this action on.


interestingly this is what I get when I type it manually

v5.4.0.124 (included with MC.Eternal)
VyrXToday at 11:15 AM
run /list and see if you're listed there
TCGJoeToday at 11:16 AM
did suggest looking on the github
Mike Hollis JrToday at 11:17 AM
[11:16:51] [Server thread/INFO] [minecraft/DedicatedServer]: There are 1/64 players online:
[11:16:51] [Server thread/INFO] [minecraft/DedicatedServer]: MikeHollisJr


I am there, the capitalization is different, but it's always been always lower case on teams, so I don't expect that to be the issue
did suggest looking on the github
Yep you did, thank you
VyrXToday at 11:20 AM
In the source code it's essentially failing at this point:

@Override
    public void clearCache()
    {
        cachedNameForChat = null;

        if (player.isOnline())
        {
            player.getPlayer().refreshDisplayName();
        }
    }

So the error in the crash log is slightly misleading
It's crashing and stating you're not online, however it's already checked if you're online and passed that statement
it then fails on player.getPlayer()
Mike Hollis JrToday at 11:25 AM
can I have your permission to include our dialog here in the issue?
VyrXToday at 11:25 AM
Ofcourse
can you check your version of ftblib for me?
Mike Hollis JrToday at 11:25 AM
sure thing one moment
5.4.4.5
VyrXToday at 11:26 AM
https://www.curseforge.com/minecraft/mc-mods/ftblib/files
install 5.4.5.0
I think that may fix your issue
Mike Hollis JrToday at 11:26 AM
does that need to be synced client and server?
VyrXToday at 11:27 AM
Yes
Mike Hollis JrToday at 11:27 AM
just so I know if I need to advise others
ok good deal let me give that a shot, it'll take 10 minutes or so
VyrXToday at 11:27 AM
Yeah sure, let me know how you get on
Mike Hollis JrToday at 11:44 AM
nah it's still doing it, not online

**Comment by SevenChords** [comment]
same thing as with MikeHollisJr happening for me

**Comment by SevenChords** [comment]
ok, i found a solution (tried 2 things, not sure which did it):
delete my playerdata from the world file
set the server to online mode=true inside the server.properties
after doing those to (didn't test in between) i could create the team no problem, maybe that will help you @MikeHollisJr

**Comment by matahombres** [comment]
@SevenChords still going
