### ISSUE TITLE
I used 1.12.2 Forge 2768,which version should i choose to download

### ISSUE THREAD

**Issue by sdsyhkkas** [FTBTeam/FTB-Utilities#934]
I used 1.12.2 Forge 2768,which version should i choose to download.
It seems higher version will make my game crash.

**Comment by LatvianModder** [comment]
try latest, it should work fine

**Comment by daniel-widrick** [comment]
You can go ahead and re-open this because information appears to be dead wrong...
```
[18:56:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod ftblib (FTB Library) requires [forge@[14.23.5.2784,)]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

https://pastebin.com/w1Pw0NUc

**Comment by daniel-widrick** [comment]
For the record.. We had had some luck with the following combo:

FTBLib-5.3.1.57.jar        FTBUtilities-5.3.0.53.jar

I doubt it is the most recent that will work with the given forge version though. 2768 is relevant because that's where spongeforge is at right now.
1.12.2 - 14.23.5.2768
